nome = str('Miguel')
sobrenome = str('Gildai')
idade = int(22)
maior_de_idade = idade >= int(18)
altura_em_metros = float(1.67)
print(f'Nome: {nome}')
print(f'Sobrenome: {sobrenome}')
print(f'Idade: {idade}')
print(f'É maior de idade?: {maior_de_idade}')
print(f'Altura em metros: {altura_em_metros}')
